---
- name: Vagrant provisionning
  hosts: all
  become: true
  connection: local
  gather_facts: no
  
  roles:
  - docker
  - compose
  
  tasks:
  - name: Manage Docker as a non-root user
    command: usermod -aG docker ubuntu
  